### ISSUE TITLE
Host the website in Ark?

### ISSUE THREAD

**Issue by eatonphil** [ark-lang/ark-lang.org#3]
It would be awesome to have the website "self-hosting". What will it take to get this web (read: unix socket) ready?

**Comment by felixangell** [comment]
@eatonphil Hmm, I'm not too sure. @raoulvdberge ??

**Comment by raoulvdberge** [comment]
We'd need to be able to import a socket library (from C?) first in the language.

**Comment by felixangell** [comment]
@raoulvdberge We just write proto's for the functions & structure definitions, then I think that'd be enough?

**Comment by raoulvdberge** [comment]
Yes!

**Comment by felixangell** [comment]
....Kind of, once arrays are fully working this will be possible :)

**Comment by bread-man** [comment]
Exciting :grinning:

**Comment by raoulvdberge** [comment]
Not relevant for now.

**Comment by felixangell** [comment]
If it's not done then we keep it open

**Comment by felixangell** [comment]
@raoulvdberge I'm pretty sure this would be possible now

**Comment by 0xbadb002** [comment]
@eatonphil This is now done :) You can see my naive little web server thing [here](//github.com/0xbadb002/shelob).

**Comment by eatonphil** [comment]
Nice!
