### ISSUE TITLE
The reference page seems to use old primitive names

### ISSUE THREAD

**Issue by SamTebbs33** [ark-lang/ark-lang.org#4]
The reference page seems to use old primitive names, such as s8, s16 et.c
AFIAK these primitives are instead called i8, i16 et.c

**Comment by felixangell** [comment]
You seem to have got it the other way round :) s8 is the new way of saying it, since you have u8 which is unsigned, and s8 which is signed.

**Comment by SamTebbs33** [comment]
Aaah I see. I thought I saw the "i8" type in one of test files, my bad :p

**Comment by felixangell** [comment]
It's all good :smile_cat:
